analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3473498,"name"\:"First Project","teamId"\:3459279,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3495242,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3459279,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
