<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_card_number</name>
   <tag></tag>
   <elementGuidId>a48fea90-b572-49ed-816d-a438499b1012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'card_number' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-qa=&quot;card-number&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-qa = 'card-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;card_number&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05350768-d3ee-4345-bf7b-6cd0669a4931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>213f3fdd-b13e-47cd-b6b6-1d1fd6d17d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>card-number</value>
      <webElementGuid>8d0d1636-659a-4913-b9c6-f80f944ebe4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control card-number</value>
      <webElementGuid>deb1d8fd-96a0-4120-8558-001793ca68c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2cf66c6e-3fb5-4975-b351-2318c1197c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c424b9cf570b1bf33909caf8b3a8d8d8</value>
      <webElementGuid>0c6c406f-3707-4296-9b99-859e2561f561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-qa = 'card-number']</value>
      <webElementGuid>9bed8776-f3de-45aa-b66e-579e585a8599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-qa = 'card-number']</value>
      <webElementGuid>2181e8b8-b4ea-4dad-9695-bd7362d07819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'card_number' and @type = 'text']</value>
      <webElementGuid>c4f3ef3f-3816-4692-befe-0a3785ab8e5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
