<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MM</name>
   <tag></tag>
   <elementGuidId>fc80b8ff-ed7a-4239-82a9-50631496a9dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'expiry_month' and @placeholder = 'MM' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-qa=&quot;expiry-month&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-qa = 'expiry-month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;MM&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ff83088-499c-46cd-a05e-967e56878b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control card-expiry-month</value>
      <webElementGuid>57a1dad4-5658-4f52-9bca-aaa55cf797c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry_month</value>
      <webElementGuid>adcb7052-28ba-4764-9519-d74c5b5cceb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>expiry-month</value>
      <webElementGuid>98c7b7e9-85b4-4d06-82ac-9b2c72d3ff2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM</value>
      <webElementGuid>097ba576-02b4-48e8-946c-cfb4b7cdd146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0890d2b-2df1-4889-ac7e-56131cd8fb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-875705dc932911ae4b0f1cedad624e66</value>
      <webElementGuid>822a7cae-1213-4bcc-8cf7-ff120f9867d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-qa = 'expiry-month']</value>
      <webElementGuid>0302ec0f-246c-4f9e-9b69-d3e547f2940a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-qa = 'expiry-month']</value>
      <webElementGuid>84eb0e89-4090-48f4-9549-814fd8939dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'expiry_month' and @placeholder = 'MM' and @type = 'text']</value>
      <webElementGuid>6bd21b06-8a65-4570-a740-5809d81a785e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
