<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_scrollUp</name>
   <tag></tag>
   <elementGuidId>65de2936-60c4-4d64-bbaf-3544358d97ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scrollUp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'scrollUp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>814a57c2-1456-4c0c-80b4-9b01b09a6990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scrollUp</value>
      <webElementGuid>fb6b05dc-3a01-464e-af03-feadc9beb060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#top</value>
      <webElementGuid>d83a2b10-76e1-4533-b368-ddf4e52265b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5283971a7b324184a32d636ca54cfeaa</value>
      <webElementGuid>04edb223-806a-4914-9e85-a17ab0aa44cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'scrollUp']</value>
      <webElementGuid>2833040d-1529-4bc9-8df6-a551bc83a4f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'scrollUp']</value>
      <webElementGuid>2a6274d1-1df6-4d97-95ca-247fda294536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'scrollUp' and @href = '#top']</value>
      <webElementGuid>0d1607e4-ed95-441e-ba76-1abf456c76cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
