<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>u_View Cart</name>
   <tag></tag>
   <elementGuidId>027b14bc-71ae-40d7-906a-219a45bd195d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>u</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//u</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;View Cart&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>d914e814-a4ef-419d-88f5-f3c01d7bf662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Cart</value>
      <webElementGuid>55311222-c78a-49fd-a78b-88d8ac360b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5d79a02b84ba1297daf6008bad3d2b77</value>
      <webElementGuid>3c925464-e578-4eb9-95e4-d3e7b45c8b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//u</value>
      <webElementGuid>ab0986cf-1f53-474a-b978-a118b18fd47d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//u</value>
      <webElementGuid>5a5cd879-ef1a-472b-9b0c-3a5cde0b765f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = 'View Cart' or . = 'View Cart')]</value>
      <webElementGuid>b37bc616-50f7-476f-8b37-466b854077f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
