<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Write Your Review</name>
   <tag></tag>
   <elementGuidId>8e355fb3-664a-45b6-8640-b8ef4c812263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-toggle=&quot;tab&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-toggle = 'tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Write Your Review&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>170c63ae-0c15-404e-9d2b-4db321ac7fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#reviews</value>
      <webElementGuid>41d52d78-ac12-4e0c-964e-f62cc9eb40af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>afcec048-613e-4806-a892-371422efd753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Write Your Review</value>
      <webElementGuid>be917ec7-cb4a-4ad6-a657-b71477d49281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f04bd68b1e6821c1bed5ca55fba7cb77</value>
      <webElementGuid>1a682ecc-2a72-4a7f-8a2b-921f9a6b5cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-toggle = 'tab']</value>
      <webElementGuid>56d27632-5b5a-4c8c-b42c-4cdd94997002</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-toggle = 'tab']</value>
      <webElementGuid>5752e224-6eae-4430-a4ed-6fe383d7ad09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#reviews' and (text() = 'Write Your Review' or . = 'Write Your Review')]</value>
      <webElementGuid>b492b4bd-5bc2-4121-b860-dcc57598addd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
