<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_(6)Polo</name>
   <tag></tag>
   <elementGuidId>369d0d6f-c880-4c8e-8b0a-7644c3a6526d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/brand_products\/Polo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/brand_products/Polo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;(6) Polo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b70ae707-5db4-4018-832a-c02d22b5bec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/brand_products/Polo</value>
      <webElementGuid>b0dcca94-8e16-4137-be29-c6c8af5910aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (6)Polo</value>
      <webElementGuid>3dcad073-f01f-4f0b-861e-0ef54b122b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0232a72a705aab3f4ca744af6edf0569</value>
      <webElementGuid>5e3d64e5-1ad8-4541-bf3f-8406d7c30bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/brand_products/Polo']</value>
      <webElementGuid>3fbb3169-a038-4dd0-b64d-cdd1bf3fe394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/brand_products/Polo']</value>
      <webElementGuid>9685f0bd-72ef-47ab-b2d2-85c08d5cbe7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/brand_products/Polo' and (text() = ' (6)Polo' or . = ' (6)Polo')]</value>
      <webElementGuid>0de4783a-6257-43e0-8afc-b9766f01650a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
