<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_submit_search</name>
   <tag></tag>
   <elementGuidId>640bdc89-a4c9-4361-843c-fada2625a0de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'submit_search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'submit_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24263e29-c95b-41aa-bbff-a987dddd7c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c89caec-cb80-4de2-b412-3691d7059e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit_search</value>
      <webElementGuid>2742acdb-169a-490f-b51c-c4357ff4bab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-lg</value>
      <webElementGuid>161351bc-161b-4c33-acf5-774ea5d155b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4ee76f674c09bfdb9a1a6d878bf70034</value>
      <webElementGuid>9fd70996-c18c-4598-84e0-cfeb4c10ec8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'submit_search']</value>
      <webElementGuid>5c8195c3-c4d5-4177-8278-fccd31871f0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'submit_search']</value>
      <webElementGuid>36494ae0-e29f-4e9d-b2c3-f60f8a462783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'submit_search']</value>
      <webElementGuid>1534fc90-cdf1-4e37-8b67-5b25f27dcaaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
