<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_(5)</name>
   <tag></tag>
   <elementGuidId>a7201584-e0f0-4096-b2a8-7fdaae84b0cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/brand_products\/H\&amp;M&quot;] span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/brand_products/H&amp;M']//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;(5) H&amp;M&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>42dc184e-15e9-47cd-9f35-482f2c9b060d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-right</value>
      <webElementGuid>86f71d30-2ea1-4394-a131-623903f23576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(5)</value>
      <webElementGuid>85068d49-8a57-4a50-a567-f308123434fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9387f9d17c119f68ed74d0672fe5dd42</value>
      <webElementGuid>c029a131-4c5c-4f78-b32a-c3777dcdb848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/brand_products/H&amp;M']//span</value>
      <webElementGuid>dfd44986-905f-4579-ae64-a172f7ca476a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/brand_products/H&amp;M']//span</value>
      <webElementGuid>e6b6bf5d-f5eb-410a-81d2-8110ffccb412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '(5)' or . = '(5)')]</value>
      <webElementGuid>a50ae695-9bd7-44a1-9840-4f8ad645d9a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
