<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mrs</name>
   <tag></tag>
   <elementGuidId>1c9ca4eb-b1f5-494f-857f-694ce2c878c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'title' and @id = 'id_gender2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;Mrs&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@value = 'Mrs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Mrs.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b4e97a4-e4d9-469b-b8e2-e958b3de1055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f27f7cd0-03fd-401a-9f15-1288d39074f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>7c466188-a309-471c-ae83-f9fadae51c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_gender2</value>
      <webElementGuid>276e0d92-9dda-46c3-ba0b-8b41b4acfde4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Mrs</value>
      <webElementGuid>85b13a82-35b7-480e-b125-c8ea75b41160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3fa3a47724d9b380608de13ea00ea5b2</value>
      <webElementGuid>457b00fa-2c61-41c0-a1f7-443540cce599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@value = 'Mrs']</value>
      <webElementGuid>a3e52557-7279-4d12-b4e8-de27331dd913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@value = 'Mrs']</value>
      <webElementGuid>caeca36f-5014-4ca0-a7ac-b209f143cf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'title' and @id = 'id_gender2']</value>
      <webElementGuid>afb33c93-dbe6-4dee-9ede-983b620d0562</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
