<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_months</name>
   <tag></tag>
   <elementGuidId>ff40db79-bf3e-4bb8-8b3d-a260951c9a87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'months' and @name = 'months' and (text() = '
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										' or . = '
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-qa=&quot;months&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-qa = 'months']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#months</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>85158372-1111-47a6-ba75-433ed1c2e67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>months</value>
      <webElementGuid>f8370813-a444-4ffc-b899-3a25a37a3120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>months</value>
      <webElementGuid>e3550aef-c1a4-49fe-be14-882499810f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>months</value>
      <webElementGuid>8f2fcec4-b6f7-4ef8-93cb-bf9edf5a077a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a8457a59-9e62-47ea-ba89-eb2da21a614e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										</value>
      <webElementGuid>e642c662-02f0-41bb-921c-abad069cdec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-90812de7c5cae77c0cb50524383b08f1</value>
      <webElementGuid>48fc62ef-276a-45d3-a1b6-405361c5f091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-qa = 'months']</value>
      <webElementGuid>df1d714a-f440-4ab1-8573-acf6cfcc7915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-qa = 'months']</value>
      <webElementGuid>69c1a0ab-92ba-4b21-9fb9-0b4af37bee7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'months' and @name = 'months' and (text() = '
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										' or . = '
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										')]</value>
      <webElementGuid>9e95cd19-01b7-4725-9dec-7bd2ae942e4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
