<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your email address</name>
   <tag></tag>
   <elementGuidId>106b265d-1afa-4bad-ab5e-da8b9bf7fbe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#susbscribe_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'susbscribe_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Your email address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>074a6775-a08c-474d-8701-d178c925dbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>88af4b4e-18f4-49fd-993e-680635498860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>susbscribe_email</value>
      <webElementGuid>8a0b28f7-0b12-40d3-918e-77ea1ca87745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your email address</value>
      <webElementGuid>58cf30b3-474c-4e97-a073-fd7fc25f0ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5fb0e7119514fff89d11c355a4a09d7a</value>
      <webElementGuid>8643a138-bbbb-4a54-9de6-521619375631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'susbscribe_email']</value>
      <webElementGuid>d14dfcbb-8666-46d1-a50f-04fbf0064087</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'susbscribe_email']</value>
      <webElementGuid>cc70fb9f-d18c-450d-960c-7dedbb772b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'susbscribe_email' and @placeholder = 'Your email address']</value>
      <webElementGuid>1132906c-6f9e-4dd5-aa27-4735e4bb4932</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
